build:
  cuda_version: "12.1.1"
  python_packages:
    - "torch==2.1.0"
    - "transformers==4.34.0"
    - "accelerate==0.23.0"
    - "bitsandbytes==0.41.1"
    - "scipy==1.11.3"
    - "Pillow==10.0.1"
    - "hf-transfer==0.1.9"
    - "huggingface-hub==0.29.1"
